[project]
name = "test-dinov3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.10.1",
    "albumentations>=2.0.8",
    "datasets>=4.2.0",
    "debugpy>=1.8.17",
    "huggingface-hub[cli]>=0.35.3",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "pycocotools>=2.0.10",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "ruff>=0.14.0",
    "torchmetrics[detection]>=1.8.2",
    "torchviz>=0.0.3",
    "transformers>=4.57.1",
    "wandb>=0.22.2",
]
